name: "[internal] publish all packages"

on:
  workflow_call:
    inputs:
      mode:
        type: string
        description: supporte values are 'release' and 'dry-run'
        required: true

jobs:
  publish-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-rust
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          mode: ${{ inputs.mode }}

  publish-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-python
        with:
          registry-token: ${{ secrets.PYPI_REGISTRY_TOKEN }}
          mode: ${{ inputs.mode }}

  publish-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-node
        with:
          registry-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          mode: ${{ inputs.mode }}

  publish-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-go
        with:
          repository-token: ${{ secrets.GOSDK_REPOSITORY_TOKEN }}
          mode: ${{ inputs.mode }}

  # publish-haskell:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: codegen
  #         path: ./codegen

  #     - uses: ./.github/actions/publish-haskell
  #       with:
  #         registry-token: ${{ secrets.HACKAGE_REGISTRY_TOKEN }}
  #         mode: ${{ inputs.mode }}

  publish-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-dotnet
        with:
          registry-token: ${{ secrets.NUGET_REGISTRY_TOKEN }}
          mode: ${{ inputs.mode }}
